# Generated by Django 4.2.15 on 2024-08-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(editable=False, max_length=10)),
                ('date', models.DateField(editable=False)),
                ('time', models.TimeField(editable=False)),
                ('selfie', models.ImageField(upload_to='selfies/')),
                ('guard', models.ForeignKey(limit_choices_to={'is_guard': True}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='security.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.OneToOneField(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='security.usertype')),
                ('managed_guards', models.ManyToManyField(limit_choices_to={'is_guard': True}, related_name='managed_by_admins', to='security.usertype')),
            ],
        ),
    ]
