# Generated by Django 4.2.15 on 2024-08-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_attendance_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='name',
        ),
    ]
